# Generated by Django 4.2.13 on 2024-06-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7, verbose_name='Вес'),
        ),
    ]
