# Generated by Django 4.2.13 on 2024-06-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_cake_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Вес'),
        ),
    ]
