# Generated by Django 4.2.13 on 2024-06-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='cake',
            name='images',
            field=models.ManyToManyField(to='cake.image', verbose_name='Изображения'),
        ),
    ]
