# Generated by Django 3.2.16 on 2024-07-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0006_alter_cake_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='decorations',
        ),
        migrations.AddField(
            model_name='cake',
            name='compound',
            field=models.TextField(default=100, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='weight',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Вес'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Decoration',
        ),
    ]
