# Generated by Django 3.2.16 on 2024-07-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0008_alter_cake_compound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='compound',
            field=models.TextField(default='200', verbose_name='Состав'),
        ),
    ]
