# Generated by Django 3.2.16 on 2024-07-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0009_alter_cake_compound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='compound',
            field=models.TextField(verbose_name='Состав'),
        ),
    ]
