# Generated by Django 3.2.16 on 2024-07-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0010_alter_cake_compound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='compound',
            new_name='composition',
        ),
    ]
