# Generated by Django 3.2.16 on 2024-07-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0012_alter_cake_composition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='composition',
        ),
    ]
